services:
  - type: web
    name: face-emotion-detector
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: true
    envVars:
      PYTHON_VERSION: 3.11.6